services:
    simplesamlphp.auth:
        class: SimpleSAML\Auth\Simple
        arguments: [ '%simplesamlphp.sp%' ]

    simplesamlphp.authenticator:
        class: Hslavich\SimplesamlphpBundle\Security\SamlAuthenticator
        arguments: [ '@simplesamlphp.auth', '@session', '%simplesamlphp.auth_attribute%' ]

    simplesamlphp.logout_handler:
        class: Hslavich\SimplesamlphpBundle\Security\Http\Logout\LogoutSuccessHandler
        arguments: [ '@simplesamlphp.auth', '@router' ]
